FloatLayout:
    Button:
        text: 'show subwindow'
        on_press: subwin.open()

    SubWindow:
        id: subwin
        title: 'my subwindow'
        pos: (50, 50)
        size: (400, 300)
        allow_native: False
        auto_open: True

#        SubWindowPopup:
#            title: 'my super popup'
#            pos: subwin.pos
#            size: subwin.size
#            type: subwin.type
